# golangci-lint configuration for Structyl
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  go: "1.22"
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Go vet checks
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Find unused code

    # Additional recommended linters
    - copyloopvar   # Detect loop variable capture issues (Go 1.22+)
    - misspell      # Check for spelling errors
    - unconvert     # Remove unnecessary type conversions

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        # Test helper functions that commonly ignore errors
        - os.Chdir
        - (net/http.ResponseWriter).Write
        - io.Copy
        - (*os/exec.Cmd).Run
        - (*compress/gzip.Writer).Close

    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck  # Tests often ignore errors intentionally

formatters:
  enable:
    - gofmt         # Check code formatting
    - goimports     # Check import organization

  settings:
    goimports:
      local-prefixes:
        - github.com/AndreyAkinshin/structyl

output:
  formats:
    text:
      print-linter-name: true
