# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: structyl

before:
  hooks:
    - go mod tidy

builds:
  - id: structyl
    main: ./cmd/structyl
    binary: structyl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/AndreyAkinshin/structyl/internal/cli.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: AndreyAkinshin
    name: structyl
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Installation

    ### Quick Install (Recommended)

    **macOS / Linux:**
    ```bash
    curl -fsSL https://get.structyl.akinshin.dev/install.sh | sh
    ```

    **Windows (PowerShell):**
    ```powershell
    irm https://get.structyl.akinshin.dev/install.ps1 | iex
    ```

    ### Install Specific Version
    ```bash
    curl -fsSL https://get.structyl.akinshin.dev/install.sh | sh -s -- --version {{.Version}}
    ```

    ### Go Install
    ```bash
    go install github.com/AndreyAkinshin/structyl/cmd/structyl@v{{.Version}}
    ```

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other"
      order: 999
