package toolchain

// GetDefaultToolchains returns the default toolchains configuration.
// This data is derived from internal/cli/toolchains_template.json which is the
// canonical source of truth for toolchain definitions.
func GetDefaultToolchains() *ToolchainsFile {
	return &ToolchainsFile{
		Schema:  "https://structyl.akinshin.dev/schemas/toolchains.json",
		Version: "1.0",
		Commands: map[string]CommandMeta{
			"clean":         {Description: "Clean build artifacts"},
			"restore":       {Description: "Restore/install dependencies"},
			"build":         {Description: "Build targets"},
			"build:release": {Description: "Build targets (release mode)"},
			"test":          {Description: "Run tests"},
			"test:coverage": {Description: "Run tests with coverage"},
			"check":         {Description: "Run static analysis (lint, typecheck, format-check)"},
			"check:fix":     {Description: "Auto-fix static analysis issues"},
			"bench":         {Description: "Run benchmarks"},
			"demo":          {Description: "Run demos"},
			"doc":           {Description: "Generate documentation"},
			"pack":          {Description: "Create package"},
			"publish":       {Description: "Publish package to registry"},
			"publish:dry":   {Description: "Dry-run publish (validate without uploading)"},
		},
		AggregateCommands: []string{
			"clean", "restore", "build", "build:release", "test", "check", "check:fix",
		},
		Pipelines: map[string][]string{
			"ci":         {"clean", "restore", "check", "build", "test"},
			"ci:release": {"clean", "restore", "check", "build:release", "test"},
		},
		Toolchains: map[string]ToolchainFileEntry{
			"cargo": {
				Mise: &MiseConfig{
					PrimaryTool: "rust",
					Version:     "stable",
				},
				Commands: map[string]interface{}{
					"clean":         "cargo clean",
					"restore":       nil,
					"build":         "cargo build",
					"build:release": "cargo build --release",
					"test":          "cargo test",
					"check":         []interface{}{"cargo clippy -- -D warnings", "cargo fmt --check"},
					"check:fix":     "cargo fmt",
					"bench":         "cargo bench",
					"pack":          "cargo package",
					"doc":           "cargo doc --no-deps",
					"demo":          "cargo run --example demo",
					"publish":       "cargo publish",
					"publish:dry":   "cargo publish --dry-run",
				},
			},
			"dotnet": {
				Mise: &MiseConfig{
					PrimaryTool: "dotnet",
					Version:     "10.0",
				},
				Commands: map[string]interface{}{
					"clean":         "dotnet clean",
					"restore":       "dotnet restore",
					"build":         "dotnet build",
					"build:release": "dotnet build -c Release",
					"test":          "dotnet test",
					"check":         "dotnet format --verify-no-changes",
					"check:fix":     "dotnet format",
					"bench":         nil,
					"pack":          "dotnet pack",
					"doc":           nil,
					"demo":          "dotnet run --project Demo",
					"publish":       "dotnet nuget push",
					"publish:dry":   nil,
				},
			},
			"go": {
				Mise: &MiseConfig{
					PrimaryTool: "go",
					Version:     "1.24",
					ExtraTools: map[string]string{
						"golangci-lint": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":       "go clean",
					"restore":     "go mod download",
					"build":       "go build ./...",
					"test":        "go test ./...",
					"check":       []interface{}{"golangci-lint run", "go vet ./...", `test -z "$(gofmt -l .)"`},
					"check:fix":   "go fmt ./...",
					"bench":       "go test -bench=. ./...",
					"pack":        nil,
					"doc":         "go doc ./...",
					"demo":        "go run ./cmd/demo",
					"publish":     nil,
					"publish:dry": nil,
				},
			},
			"npm": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
				},
				Commands: map[string]interface{}{
					"clean":       "npm run clean",
					"restore":     "npm ci",
					"build":       "npm run build",
					"test":        "npm test",
					"check":       []interface{}{"npm run lint", "npm run typecheck", "npm run format:check"},
					"check:fix":   []interface{}{"npm run lint -- --fix", "npm run format"},
					"bench":       nil,
					"pack":        "npm pack",
					"doc":         nil,
					"demo":        "npm run demo",
					"publish":     "npm publish",
					"publish:dry": "npm publish --dry-run",
				},
			},
			"pnpm": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
					ExtraTools: map[string]string{
						"pnpm": "10",
					},
				},
				Commands: map[string]interface{}{
					"clean":       "pnpm run clean",
					"restore":     "pnpm install --frozen-lockfile",
					"build":       "pnpm build",
					"test":        "pnpm test",
					"check":       []interface{}{"pnpm lint", "pnpm typecheck", "pnpm format:check"},
					"check:fix":   []interface{}{"pnpm lint --fix", "pnpm format"},
					"bench":       nil,
					"pack":        "pnpm pack",
					"doc":         nil,
					"demo":        "pnpm run demo",
					"publish":     "pnpm publish",
					"publish:dry": "pnpm publish --dry-run",
				},
			},
			"yarn": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
				},
				Commands: map[string]interface{}{
					"clean":       "yarn clean",
					"restore":     "yarn install --frozen-lockfile",
					"build":       "yarn build",
					"test":        "yarn test",
					"check":       []interface{}{"yarn lint", "yarn typecheck", "yarn format:check"},
					"check:fix":   []interface{}{"yarn lint --fix", "yarn format"},
					"bench":       nil,
					"pack":        "yarn pack",
					"doc":         nil,
					"demo":        "yarn run demo",
					"publish":     "yarn npm publish",
					"publish:dry": "yarn npm publish --dry-run",
				},
			},
			"bun": {
				Mise: &MiseConfig{
					PrimaryTool: "bun",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":       "bun run clean",
					"restore":     "bun install --frozen-lockfile",
					"build":       "bun run build",
					"test":        "bun test",
					"check":       []interface{}{"bun run lint", "bun run typecheck", "bun run format:check"},
					"check:fix":   []interface{}{"bun run lint --fix", "bun run format"},
					"bench":       nil,
					"pack":        "bun pm pack",
					"doc":         nil,
					"demo":        "bun run demo",
					"publish":     "bun publish",
					"publish:dry": "bun publish --dry-run",
				},
			},
			"python": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
				},
				Commands: map[string]interface{}{
					"clean":       "rm -rf dist/ build/ *.egg-info **/__pycache__/",
					"restore":     "pip install -e .",
					"build":       "python -m build",
					"test":        "pytest",
					"check":       []interface{}{"ruff check .", "mypy .", "ruff format --check ."},
					"check:fix":   []interface{}{"ruff check --fix .", "ruff format ."},
					"bench":       nil,
					"pack":        "python -m build",
					"doc":         nil,
					"demo":        "python demo.py",
					"publish":     "twine upload dist/*",
					"publish:dry": nil,
				},
			},
			"uv": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
					ExtraTools: map[string]string{
						"uv":   "0.6",
						"ruff": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":       "rm -rf dist/ build/ *.egg-info .venv/",
					"restore":     "uv sync --all-extras",
					"build":       "uv build",
					"test":        "uv run pytest",
					"check":       []interface{}{"uv run ruff check .", "uv run mypy .", "uv run ruff format --check ."},
					"check:fix":   []interface{}{"uv run ruff check --fix .", "uv run ruff format ."},
					"bench":       nil,
					"pack":        "uv build",
					"doc":         nil,
					"demo":        "uv run python demo.py",
					"publish":     "uv publish",
					"publish:dry": nil,
				},
			},
			"poetry": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
				},
				Commands: map[string]interface{}{
					"clean":       "rm -rf dist/",
					"restore":     "poetry install",
					"build":       "poetry build",
					"test":        "poetry run pytest",
					"check":       []interface{}{"poetry run ruff check .", "poetry run mypy .", "poetry run ruff format --check ."},
					"check:fix":   []interface{}{"poetry run ruff check --fix .", "poetry run ruff format ."},
					"bench":       nil,
					"pack":        "poetry build",
					"doc":         nil,
					"demo":        "poetry run python demo.py",
					"publish":     "poetry publish",
					"publish:dry": "poetry publish --dry-run",
				},
			},
			"gradle": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
				},
				Commands: map[string]interface{}{
					"clean":       "gradle clean",
					"restore":     nil,
					"build":       "gradle build -x test",
					"test":        "gradle test",
					"check":       []interface{}{"gradle check -x test", "gradle spotlessCheck"},
					"check:fix":   "gradle spotlessApply",
					"bench":       nil,
					"pack":        "gradle jar",
					"doc":         "gradle javadoc",
					"demo":        "gradle run",
					"publish":     "gradle publish",
					"publish:dry": nil,
				},
			},
			"maven": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
				},
				Commands: map[string]interface{}{
					"clean":       "mvn clean",
					"restore":     "mvn dependency:resolve",
					"build":       "mvn compile",
					"test":        "mvn test",
					"check":       []interface{}{"mvn checkstyle:check", "mvn spotless:check"},
					"check:fix":   "mvn spotless:apply",
					"bench":       nil,
					"pack":        "mvn package -DskipTests",
					"doc":         "mvn javadoc:javadoc",
					"demo":        "mvn exec:java",
					"publish":     "mvn deploy",
					"publish:dry": nil,
				},
			},
			"make": {
				Mise: nil,
				Commands: map[string]interface{}{
					"clean":         "make clean",
					"restore":       nil,
					"build":         "make",
					"build:release": "make release",
					"test":          "make test",
					"check":         "make check",
					"check:fix":     "make fix",
					"bench":         "make bench",
					"pack":          "make dist",
					"doc":           "make doc",
					"demo":          "make demo",
					"publish":       "make publish",
					"publish:dry":   "make publish-dry",
				},
			},
			"cmake": {
				Mise: &MiseConfig{
					PrimaryTool: "cmake",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":       "cmake --build build --target clean",
					"restore":     "cmake -B build -S .",
					"build":       "cmake --build build",
					"test":        "ctest --test-dir build",
					"check":       []interface{}{"cmake --build build --target lint", "cmake --build build --target format-check"},
					"check:fix":   "cmake --build build --target format",
					"bench":       nil,
					"pack":        "cmake --build build --target package",
					"doc":         "cmake --build build --target doc",
					"demo":        "cmake --build build --target demo && ./build/demo",
					"publish":     nil,
					"publish:dry": nil,
				},
			},
			"swift": {
				Mise: &MiseConfig{
					PrimaryTool: "swift",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         "swift package clean",
					"restore":       "swift package resolve",
					"build":         "swift build",
					"build:release": "swift build -c release",
					"test":          "swift test",
					"check":         []interface{}{"swiftlint", "swiftformat --lint ."},
					"check:fix":     []interface{}{"swiftlint --fix", "swiftformat ."},
					"bench":         nil,
					"pack":          nil,
					"doc":           nil,
					"demo":          "swift run Demo",
					"publish":       nil,
					"publish:dry":   nil,
				},
			},
			"r": {
				Mise: &MiseConfig{
					PrimaryTool: "r",
					Version:     "4.4",
				},
				Commands: map[string]interface{}{
					"clean":       "rm -rf *.tar.gz *.Rcheck/",
					"restore":     nil,
					"build":       "R CMD build .",
					"test":        "Rscript -e \"devtools::test()\"",
					"check":       []interface{}{"Rscript -e \"lintr::lint_package()\"", "Rscript -e \"styler::style_pkg(dry='on')\""},
					"check:fix":   "Rscript -e \"styler::style_pkg()\"",
					"bench":       nil,
					"pack":        "R CMD build .",
					"doc":         "Rscript -e \"roxygen2::roxygenise()\"",
					"demo":        "Rscript demo.R",
					"publish":     "Rscript -e \"devtools::release()\"",
					"publish:dry": nil,
				},
			},
			"deno": {
				Mise: &MiseConfig{
					PrimaryTool: "deno",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":       nil,
					"restore":     "deno install",
					"build":       nil,
					"test":        "deno test",
					"check":       []interface{}{"deno lint", "deno check **/*.ts", "deno fmt --check"},
					"check:fix":   "deno fmt",
					"bench":       "deno bench",
					"doc":         "deno doc",
					"demo":        "deno run demo.ts",
					"publish":     "deno publish",
					"publish:dry": "deno publish --dry-run",
				},
			},
			"bundler": {
				Mise: &MiseConfig{
					PrimaryTool: "ruby",
					Version:     "3.4",
				},
				Commands: map[string]interface{}{
					"clean":       "bundle clean",
					"restore":     "bundle install",
					"build":       "bundle exec rake build",
					"test":        "bundle exec rake test",
					"check":       "bundle exec rubocop",
					"check:fix":   "bundle exec rubocop -a",
					"bench":       nil,
					"pack":        "gem build *.gemspec",
					"doc":         "bundle exec yard doc",
					"demo":        "bundle exec ruby demo.rb",
					"publish":     "gem push *.gem",
					"publish:dry": nil,
				},
			},
			"composer": {
				Mise: &MiseConfig{
					PrimaryTool: "php",
					Version:     "8.4",
				},
				Commands: map[string]interface{}{
					"clean":       nil,
					"restore":     "composer install",
					"build":       nil,
					"test":        "composer test",
					"check":       []interface{}{"composer run-script lint", "composer run-script format:check"},
					"check:fix":   "composer run-script format",
					"bench":       nil,
					"doc":         nil,
					"demo":        "php demo.php",
					"publish":     nil,
					"publish:dry": nil,
				},
			},
			"mix": {
				Mise: &MiseConfig{
					PrimaryTool: "elixir",
					Version:     "1.18",
				},
				Commands: map[string]interface{}{
					"clean":       "mix clean",
					"restore":     "mix deps.get",
					"build":       "mix compile",
					"test":        "mix test",
					"check":       []interface{}{"mix credo", "mix dialyzer", "mix format --check-formatted"},
					"check:fix":   "mix format",
					"bench":       nil,
					"doc":         "mix docs",
					"demo":        "mix run demo.exs",
					"publish":     "mix hex.publish",
					"publish:dry": "mix hex.publish --dry-run",
				},
			},
			"sbt": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
					ExtraTools: map[string]string{
						"sbt": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":       "sbt clean",
					"restore":     "sbt update",
					"build":       "sbt compile",
					"test":        "sbt test",
					"check":       "sbt scalafmtCheck",
					"check:fix":   "sbt scalafmt",
					"bench":       nil,
					"pack":        "sbt package",
					"doc":         "sbt doc",
					"demo":        "sbt run",
					"publish":     "sbt publish",
					"publish:dry": nil,
				},
			},
			"cabal": {
				Mise: &MiseConfig{
					PrimaryTool: "ghc",
					Version:     "9.12",
				},
				Commands: map[string]interface{}{
					"clean":       "cabal clean",
					"restore":     "cabal update",
					"build":       "cabal build",
					"test":        "cabal test",
					"check":       []interface{}{"cabal check", "hlint .", "ormolu --mode check $(find . -name '*.hs')"},
					"check:fix":   "ormolu --mode inplace $(find . -name '*.hs')",
					"bench":       "cabal bench",
					"doc":         "cabal haddock",
					"demo":        "cabal run",
					"publish":     "cabal upload",
					"publish:dry": "cabal upload --candidate",
				},
			},
			"stack": {
				Mise: &MiseConfig{
					PrimaryTool: "ghc",
					Version:     "9.12",
				},
				Commands: map[string]interface{}{
					"clean":       "stack clean",
					"restore":     "stack setup",
					"build":       "stack build",
					"test":        "stack test",
					"check":       []interface{}{"stack exec -- hlint .", "stack exec -- ormolu --mode check $(find . -name '*.hs')"},
					"check:fix":   "stack exec -- ormolu --mode inplace $(find . -name '*.hs')",
					"bench":       "stack bench",
					"doc":         "stack haddock",
					"demo":        "stack run",
					"publish":     "stack upload",
					"publish:dry": "stack upload --candidate",
				},
			},
			"dune": {
				Mise: &MiseConfig{
					PrimaryTool: "ocaml",
					Version:     "5.3",
				},
				Commands: map[string]interface{}{
					"clean":       "dune clean",
					"restore":     "opam install . --deps-only",
					"build":       "dune build",
					"test":        "dune runtest",
					"check":       "dune fmt --preview",
					"check:fix":   "dune fmt",
					"bench":       nil,
					"doc":         "dune build @doc",
					"demo":        "dune exec demo",
					"publish":     "opam publish",
					"publish:dry": nil,
				},
			},
			"lein": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
					ExtraTools: map[string]string{
						"leiningen": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":       "lein clean",
					"restore":     "lein deps",
					"build":       "lein compile",
					"test":        "lein test",
					"check":       []interface{}{"lein check", "lein eastwood", "lein cljfmt check"},
					"check:fix":   "lein cljfmt fix",
					"bench":       nil,
					"pack":        "lein jar",
					"doc":         "lein codox",
					"demo":        "lein run",
					"publish":     "lein deploy clojars",
					"publish:dry": nil,
				},
			},
			"zig": {
				Mise: &MiseConfig{
					PrimaryTool: "zig",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         nil,
					"restore":       nil,
					"build":         "zig build",
					"build:release": "zig build -Doptimize=ReleaseFast",
					"test":          "zig build test",
					"check":         "zig fmt --check .",
					"check:fix":     "zig fmt .",
					"bench":         nil,
					"demo":          "zig build run",
					"publish":       nil,
					"publish:dry":   nil,
				},
			},
			"rebar3": {
				Mise: &MiseConfig{
					PrimaryTool: "erlang",
					Version:     "27",
				},
				Commands: map[string]interface{}{
					"clean":       "rebar3 clean",
					"restore":     "rebar3 get-deps",
					"build":       "rebar3 compile",
					"test":        "rebar3 eunit",
					"check":       []interface{}{"rebar3 dialyzer", "rebar3 lint"},
					"check:fix":   "rebar3 format",
					"bench":       nil,
					"pack":        "rebar3 tar",
					"doc":         "rebar3 edoc",
					"demo":        "rebar3 shell",
					"publish":     "rebar3 hex publish",
					"publish:dry": "rebar3 hex publish --dry-run",
				},
			},
		},
	}
}
