package toolchain

// GetDefaultToolchains returns the default toolchains configuration.
// This consolidates both command definitions and mise tool mappings.
func GetDefaultToolchains() *ToolchainsFile {
	return &ToolchainsFile{
		Schema:  "https://structyl.akinshin.dev/schemas/toolchains.json",
		Version: "1.0",
		Toolchains: map[string]ToolchainFileEntry{
			"cargo": {
				Mise: &MiseConfig{
					PrimaryTool: "rust",
					Version:     "stable",
				},
				Commands: map[string]interface{}{
					"clean":         "cargo clean",
					"restore":       nil,
					"build":         "cargo build",
					"build:release": "cargo build --release",
					"build:verbose": "cargo build -v",
					"build:quiet":   "cargo build -q",
					"test":          "cargo test",
					"test:unit":     "cargo test --lib",
					"test:doc":      "cargo test --doc",
					"test:verbose":  "cargo test -- --nocapture",
					"test:quiet":    "cargo test -q",
					"check":         []interface{}{"lint", "format-check"},
					"lint":          "cargo clippy -- -D warnings",
					"format":        "cargo fmt",
					"format-check":  "cargo fmt --check",
					"bench":         "cargo bench",
					"pack":          "cargo package",
					"doc":           "cargo doc --no-deps",
					"demo":          "cargo run --example demo",
					"publish":       "cargo publish --dry-run",
					"test:coverage": "cargo llvm-cov",
					"coverage":      "cargo llvm-cov",
				},
			},
			"dotnet": {
				Mise: &MiseConfig{
					PrimaryTool: "dotnet",
					Version:     "10.0",
				},
				Commands: map[string]interface{}{
					"clean":         "dotnet clean",
					"restore":       "dotnet restore",
					"build":         "dotnet build",
					"build:release": "dotnet build -c Release",
					"build:verbose": "dotnet build -v detailed",
					"build:quiet":   "dotnet build -v quiet",
					"test":          "dotnet test",
					"test:release":  "dotnet test -c Release",
					"test:verbose":  "dotnet test -v detailed",
					"test:quiet":    "dotnet test -v quiet",
					"check":         "dotnet format --verify-no-changes",
					"lint":          "dotnet format --verify-no-changes",
					"format":        "dotnet format",
					"format-check":  "dotnet format --verify-no-changes",
					"bench":         nil,
					"pack":          "dotnet pack",
					"pack:release":  "dotnet pack -c Release",
					"doc":           nil,
					"demo":          "dotnet run --project Demo",
					"publish":       "dotnet publish",
					"watch":         "dotnet watch run",
					"test:coverage": "dotnet test --collect:\"XPlat Code Coverage\"",
					"coverage":      "dotnet test --collect:\"XPlat Code Coverage\"",
				},
			},
			"go": {
				Mise: &MiseConfig{
					PrimaryTool: "go",
					Version:     "1.24",
					ExtraTools: map[string]string{
						"golangci-lint": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":         "go clean",
					"restore":       "go mod download",
					"build":         "go build ./...",
					"build:verbose": "go build -v ./...",
					"build:quiet":   "go build ./...",
					"test":          "go test ./...",
					"test:verbose":  "go test -v ./...",
					"test:quiet":    "go test ./...",
					"test:coverage": "go test -cover ./...",
					"check":         []interface{}{"lint", "format-check"},
					"lint":          "golangci-lint run",
					"vet":           "go vet ./...",
					"format":        "go fmt ./...",
					"format-check":  `test -z "$(gofmt -l .)"`,
					"bench":         "go test -bench=. ./...",
					"pack":          nil,
					"doc":           "go doc ./...",
					"demo":          "go run ./cmd/demo",
					"deps":          "go mod tidy",
					"coverage":      "go test -cover ./...",
					"generate":      "go generate ./...",
				},
			},
			"npm": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
				},
				Commands: map[string]interface{}{
					"clean":         "npm run clean",
					"restore":       "npm ci",
					"build":         "npm run build",
					"test":          "npm test",
					"test:verbose":  "npm test -- --verbose",
					"test:quiet":    "npm test --silent",
					"test:coverage": "npm run test:coverage",
					"check":         []interface{}{"lint", "typecheck", "format-check"},
					"lint":          "npm run lint",
					"typecheck":     "npm run typecheck",
					"format":        "npm run format",
					"format-check":  "npm run format:check",
					"bench":         nil,
					"pack":          "npm pack",
					"doc":           nil,
					"demo":          "npm run demo",
					"install":       "npm install",
					"watch":         "npm run test:watch",
					"coverage":      "npm run test:coverage",
				},
			},
			"pnpm": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
					ExtraTools: map[string]string{
						"pnpm": "10",
					},
				},
				Commands: map[string]interface{}{
					"clean":         "pnpm run clean",
					"restore":       "pnpm install --frozen-lockfile",
					"build":         "pnpm build",
					"test":          "pnpm test",
					"test:verbose":  "pnpm test -- --verbose",
					"test:quiet":    "pnpm test --silent",
					"test:coverage": "pnpm test:coverage",
					"check":         []interface{}{"lint", "typecheck", "format-check"},
					"lint":          "pnpm lint",
					"typecheck":     "pnpm typecheck",
					"format":        "pnpm format",
					"format-check":  "pnpm format:check",
					"bench":         nil,
					"pack":          "pnpm pack",
					"doc":           nil,
					"demo":          "pnpm run demo",
					"install":       "pnpm install",
					"watch":         "pnpm run test:watch",
					"coverage":      "pnpm test:coverage",
				},
			},
			"yarn": {
				Mise: &MiseConfig{
					PrimaryTool: "node",
					Version:     "22",
				},
				Commands: map[string]interface{}{
					"clean":         "yarn clean",
					"restore":       "yarn install --frozen-lockfile",
					"build":         "yarn build",
					"test":          "yarn test",
					"test:verbose":  "yarn test --verbose",
					"test:quiet":    "yarn test --silent",
					"test:coverage": "yarn test:coverage",
					"check":         []interface{}{"lint", "typecheck", "format-check"},
					"lint":          "yarn lint",
					"typecheck":     "yarn typecheck",
					"format":        "yarn format",
					"format-check":  "yarn format:check",
					"bench":         nil,
					"pack":          "yarn pack",
					"doc":           nil,
					"demo":          "yarn run demo",
					"install":       "yarn install",
					"watch":         "yarn run test:watch",
					"coverage":      "yarn test:coverage",
				},
			},
			"bun": {
				Mise: &MiseConfig{
					PrimaryTool: "bun",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         "bun run clean",
					"restore":       "bun install --frozen-lockfile",
					"build":         "bun run build",
					"test":          "bun test",
					"test:verbose":  "bun test --verbose",
					"test:quiet":    "bun test",
					"test:coverage": "bun test --coverage",
					"check":         []interface{}{"lint", "typecheck", "format-check"},
					"lint":          "bun run lint",
					"typecheck":     "bun run typecheck",
					"format":        "bun run format",
					"format-check":  "bun run format:check",
					"bench":         nil,
					"pack":          "bun pm pack",
					"doc":           nil,
					"demo":          "bun run demo",
					"install":       "bun install",
					"watch":         "bun run test:watch",
					"coverage":      "bun test --coverage",
				},
			},
			"python": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
				},
				Commands: map[string]interface{}{
					"clean":         "rm -rf dist/ build/ *.egg-info **/__pycache__/",
					"restore":       "pip install -e .",
					"build":         "python -m build",
					"test":          "pytest",
					"test:coverage": "pytest --cov",
					"check":         []interface{}{"lint", "format-check"},
					"lint":          "ruff check .",
					"typecheck":     "mypy .",
					"format":        "ruff format .",
					"format-check":  "ruff format --check .",
					"bench":         nil,
					"pack":          "python -m build",
					"doc":           nil,
					"demo":          "python demo.py",
					"install":       "pip install -e .",
					"coverage":      "pytest --cov",
					"publish":       "twine upload dist/*",
				},
			},
			"uv": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
					ExtraTools: map[string]string{
						"uv":   "0.6",
						"ruff": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":         "rm -rf dist/ build/ *.egg-info .venv/",
					"restore":       "uv sync --all-extras",
					"build":         "uv build",
					"test":          "uv run pytest",
					"test:coverage": "uv run pytest --cov",
					"check":         []interface{}{"lint", "format-check"},
					"lint":          "uv run ruff check .",
					"typecheck":     "uv run mypy .",
					"format":        "uv run ruff format .",
					"format-check":  "uv run ruff format --check .",
					"bench":         nil,
					"pack":          "uv build",
					"doc":           nil,
					"demo":          "uv run python demo.py",
					"install":       "uv sync --all-extras",
					"coverage":      "uv run pytest --cov",
					"publish":       "uv publish",
				},
			},
			"poetry": {
				Mise: &MiseConfig{
					PrimaryTool: "python",
					Version:     "3.13",
				},
				Commands: map[string]interface{}{
					"clean":         "rm -rf dist/",
					"restore":       "poetry install",
					"build":         "poetry build",
					"test":          "poetry run pytest",
					"test:coverage": "poetry run pytest --cov",
					"check":         []interface{}{"lint", "format-check"},
					"lint":          "poetry run ruff check .",
					"typecheck":     "poetry run mypy .",
					"format":        "poetry run ruff format .",
					"format-check":  "poetry run ruff format --check .",
					"bench":         nil,
					"pack":          "poetry build",
					"doc":           nil,
					"demo":          "poetry run python demo.py",
					"install":       "poetry install",
					"coverage":      "poetry run pytest --cov",
					"publish":       "poetry publish",
				},
			},
			"gradle": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
				},
				Commands: map[string]interface{}{
					"clean":         "gradle clean",
					"restore":       nil,
					"build":         "gradle build -x test",
					"test":          "gradle test",
					"check":         "gradle check -x test",
					"lint":          "gradle check -x test",
					"format":        "gradle spotlessApply",
					"format-check":  "gradle spotlessCheck",
					"bench":         nil,
					"pack":          "gradle jar",
					"doc":           "gradle javadoc",
					"demo":          "gradle run",
					"jar":           "gradle jar",
					"deps":          "gradle dependencies",
					"test:coverage": "gradle test jacocoTestReport",
					"coverage":      "gradle test jacocoTestReport",
				},
			},
			"maven": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
				},
				Commands: map[string]interface{}{
					"clean":         "mvn clean",
					"restore":       "mvn dependency:resolve",
					"build":         "mvn compile",
					"test":          "mvn test",
					"check":         "mvn verify -DskipTests",
					"lint":          "mvn checkstyle:check",
					"format":        "mvn spotless:apply",
					"format-check":  "mvn spotless:check",
					"bench":         nil,
					"pack":          "mvn package -DskipTests",
					"doc":           "mvn javadoc:javadoc",
					"demo":          "mvn exec:java",
					"jar":           "mvn package -DskipTests",
					"deps":          "mvn dependency:resolve",
					"test:coverage": "mvn verify -Djacoco.skip=false",
					"coverage":      "mvn verify -Djacoco.skip=false",
				},
			},
			"make": {
				Mise: nil, // make toolchain has no mise support
				Commands: map[string]interface{}{
					"clean":         "make clean",
					"restore":       nil,
					"build":         "make",
					"build:release": "make release",
					"test":          "make test",
					"check":         "make check",
					"lint":          "make lint",
					"format":        "make format",
					"format-check":  nil,
					"bench":         "make bench",
					"pack":          "make dist",
					"doc":           "make doc",
					"demo":          "make demo",
				},
			},
			"cmake": {
				Mise: &MiseConfig{
					PrimaryTool: "cmake",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":           "cmake --build build --target clean",
					"restore":         "cmake -B build -S .",
					"restore:release": "cmake -B build -S . -DCMAKE_BUILD_TYPE=Release",
					"build":           "cmake --build build",
					"test":            "ctest --test-dir build",
					"check":           nil,
					"lint":            "cmake --build build --target lint",
					"format":          "cmake --build build --target format",
					"format-check":    "cmake --build build --target format-check",
					"bench":           nil,
					"pack":            "cmake --build build --target package",
					"doc":             "cmake --build build --target doc",
					"demo":            "cmake --build build --target demo && ./build/demo",
				},
			},
			"swift": {
				Mise: &MiseConfig{
					PrimaryTool: "swift",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         "swift package clean",
					"restore":       "swift package resolve",
					"build":         "swift build",
					"build:release": "swift build -c release",
					"test":          "swift test",
					"check":         nil,
					"lint":          "swiftlint",
					"format":        "swiftformat .",
					"format-check":  "swiftformat --lint .",
					"bench":         nil,
					"pack":          nil,
					"doc":           nil,
					"demo":          "swift run Demo",
					"test:coverage": "swift test --enable-code-coverage",
					"coverage":      "swift test --enable-code-coverage",
				},
			},
			"r": {
				Mise: &MiseConfig{
					PrimaryTool: "r",
					Version:     "4.4",
				},
				Commands: map[string]interface{}{
					"clean":        "rm -rf *.tar.gz *.Rcheck/",
					"restore":      nil,
					"build":        "R CMD build .",
					"test":         "Rscript -e \"devtools::test()\"",
					"check":        "R CMD check --no-manual --no-tests *.tar.gz",
					"check:full":   "R CMD check --as-cran *.tar.gz",
					"lint":         "Rscript -e \"lintr::lint_package()\"",
					"format":       "Rscript -e \"styler::style_pkg()\"",
					"format-check": "Rscript -e \"styler::style_pkg(dry='on')\"",
					"bench":        nil,
					"pack":         "R CMD build .",
					"doc":          "Rscript -e \"roxygen2::roxygenise()\"",
					"demo":         "Rscript demo.R",
					"install":      "R CMD INSTALL .",
				},
			},
			"deno": {
				Mise: &MiseConfig{
					PrimaryTool: "deno",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         nil,
					"restore":       "deno install",
					"build":         nil,
					"test":          "deno test",
					"test:coverage": "deno test --coverage",
					"check":         []interface{}{"lint", "typecheck"},
					"lint":          "deno lint",
					"typecheck":     "deno check **/*.ts",
					"format":        "deno fmt",
					"format-check":  "deno fmt --check",
					"bench":         "deno bench",
					"doc":           "deno doc",
					"demo":          "deno run demo.ts",
					"coverage":      "deno test --coverage",
				},
			},
			"bundler": {
				Mise: &MiseConfig{
					PrimaryTool: "ruby",
					Version:     "3.4",
				},
				Commands: map[string]interface{}{
					"clean":         "bundle clean",
					"restore":       "bundle install",
					"build":         "bundle exec rake build",
					"test":          "bundle exec rake test",
					"test:coverage": "bundle exec rake test COVERAGE=true",
					"check":         []interface{}{"lint"},
					"lint":          "bundle exec rubocop",
					"format":        "bundle exec rubocop -a",
					"format-check":  "bundle exec rubocop --format offenses --fail-level convention",
					"bench":         nil,
					"pack":          "gem build *.gemspec",
					"doc":           "bundle exec yard doc",
					"demo":          "bundle exec ruby demo.rb",
					"publish":       "gem push *.gem",
					"coverage":      "bundle exec rake test COVERAGE=true",
				},
			},
			"composer": {
				Mise: &MiseConfig{
					PrimaryTool: "php",
					Version:     "8.4",
				},
				Commands: map[string]interface{}{
					"clean":         nil,
					"restore":       "composer install",
					"build":         nil,
					"test":          "composer test",
					"test:coverage": "composer test -- --coverage",
					"check":         []interface{}{"lint"},
					"lint":          "composer run-script lint",
					"format":        "composer run-script format",
					"format-check":  "composer run-script format:check",
					"bench":         nil,
					"doc":           nil,
					"demo":          "php demo.php",
					"coverage":      "composer test -- --coverage",
				},
			},
			"mix": {
				Mise: &MiseConfig{
					PrimaryTool: "elixir",
					Version:     "1.18",
				},
				Commands: map[string]interface{}{
					"clean":         "mix clean",
					"restore":       "mix deps.get",
					"build":         "mix compile",
					"test":          "mix test",
					"test:coverage": "mix test --cover",
					"check":         []interface{}{"lint", "typecheck"},
					"lint":          "mix credo",
					"typecheck":     "mix dialyzer",
					"format":        "mix format",
					"format-check":  "mix format --check-formatted",
					"bench":         nil,
					"doc":           "mix docs",
					"demo":          "mix run demo.exs",
					"deps":          "mix deps.get",
					"publish":       "mix hex.publish",
					"coverage":      "mix test --cover",
				},
			},
			"sbt": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
					ExtraTools: map[string]string{
						"sbt": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":         "sbt clean",
					"restore":       "sbt update",
					"build":         "sbt compile",
					"test":          "sbt test",
					"check":         "sbt scalafmtCheck",
					"lint":          "sbt scalafmtCheck",
					"format":        "sbt scalafmt",
					"format-check":  "sbt scalafmtCheck",
					"bench":         nil,
					"pack":          "sbt package",
					"doc":           "sbt doc",
					"demo":          "sbt run",
					"publish":       "sbt publish",
					"test:coverage": "sbt coverage test coverageReport",
					"coverage":      "sbt coverage test coverageReport",
				},
			},
			"cabal": {
				Mise: &MiseConfig{
					PrimaryTool: "ghc",
					Version:     "9.12",
				},
				Commands: map[string]interface{}{
					"clean":         "cabal clean",
					"restore":       "cabal update",
					"build":         "cabal build",
					"test":          "cabal test",
					"check":         "cabal check",
					"lint":          "hlint .",
					"format":        "ormolu --mode inplace $(find . -name '*.hs')",
					"format-check":  "ormolu --mode check $(find . -name '*.hs')",
					"bench":         "cabal bench",
					"doc":           "cabal haddock",
					"demo":          "cabal run",
					"publish":       "cabal upload",
					"test:coverage": "cabal test --enable-coverage",
					"coverage":      "cabal test --enable-coverage",
				},
			},
			"stack": {
				Mise: &MiseConfig{
					PrimaryTool: "ghc",
					Version:     "9.12",
				},
				Commands: map[string]interface{}{
					"clean":         "stack clean",
					"restore":       "stack setup",
					"build":         "stack build",
					"test":          "stack test",
					"check":         nil,
					"lint":          "stack exec -- hlint .",
					"format":        "stack exec -- ormolu --mode inplace $(find . -name '*.hs')",
					"format-check":  "stack exec -- ormolu --mode check $(find . -name '*.hs')",
					"bench":         "stack bench",
					"doc":           "stack haddock",
					"demo":          "stack run",
					"publish":       "stack upload",
					"test:coverage": "stack test --coverage",
					"coverage":      "stack test --coverage",
				},
			},
			"dune": {
				Mise: &MiseConfig{
					PrimaryTool: "ocaml",
					Version:     "5.3",
				},
				Commands: map[string]interface{}{
					"clean":         "dune clean",
					"restore":       "opam install . --deps-only",
					"build":         "dune build",
					"test":          "dune runtest",
					"check":         nil,
					"lint":          nil,
					"format":        "dune fmt",
					"format-check":  "dune fmt --preview",
					"bench":         nil,
					"doc":           "dune build @doc",
					"demo":          "dune exec demo",
					"test:coverage": "dune runtest --instrument-with bisect_ppx",
					"coverage":      "dune runtest --instrument-with bisect_ppx",
				},
			},
			"lein": {
				Mise: &MiseConfig{
					PrimaryTool: "java",
					Version:     "temurin-23",
					ExtraTools: map[string]string{
						"leiningen": "latest",
					},
				},
				Commands: map[string]interface{}{
					"clean":         "lein clean",
					"restore":       "lein deps",
					"build":         "lein compile",
					"test":          "lein test",
					"check":         "lein check",
					"lint":          "lein eastwood",
					"format":        "lein cljfmt fix",
					"format-check":  "lein cljfmt check",
					"bench":         nil,
					"pack":          "lein jar",
					"doc":           "lein codox",
					"demo":          "lein run",
					"publish":       "lein deploy clojars",
					"test:coverage": "lein cloverage",
					"coverage":      "lein cloverage",
				},
			},
			"zig": {
				Mise: &MiseConfig{
					PrimaryTool: "zig",
					Version:     "latest",
				},
				Commands: map[string]interface{}{
					"clean":         nil,
					"restore":       nil,
					"build":         "zig build",
					"build:release": "zig build -Doptimize=ReleaseFast",
					"test":          "zig build test",
					"check":         nil,
					"lint":          nil,
					"format":        "zig fmt .",
					"format-check":  "zig fmt --check .",
					"bench":         nil,
					"demo":          "zig build run",
				},
			},
			"rebar3": {
				Mise: &MiseConfig{
					PrimaryTool: "erlang",
					Version:     "27",
				},
				Commands: map[string]interface{}{
					"clean":         "rebar3 clean",
					"restore":       "rebar3 get-deps",
					"build":         "rebar3 compile",
					"test":          "rebar3 eunit",
					"test:ct":       "rebar3 ct",
					"check":         "rebar3 dialyzer",
					"lint":          "rebar3 lint",
					"format":        "rebar3 format",
					"format-check":  nil,
					"bench":         nil,
					"pack":          "rebar3 tar",
					"doc":           "rebar3 edoc",
					"demo":          "rebar3 shell",
					"publish":       "rebar3 hex publish",
					"test:coverage": "rebar3 cover",
					"coverage":      "rebar3 cover",
				},
			},
		},
	}
}
